apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-flask
  namespace: wikins
  labels:
    app: wiki
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wiki
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki
        image: gerrp/wiki:8
        ports:
        - containerPort: 5000