apiVersion: v1
kind: Service
metadata:
  name: wiki-nodeport
  namespace: wikins
spec:
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort