apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeport }}
  namespace: {{ .Values.namespace }}
spec: 
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  type: NodePort