name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "docker/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
            dockerfile: docker/dockerfile
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker build
        run: docker build ./docker -t ${{ secrets.DOCKERHUB_USERNAME }}/wiki:${{ github.run_number }}

      - 
        name: Set up Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.21.0/trivy_0.21.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.21.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/trivy
          trivy --version

      -
        name: Run Trivy vulnerability scanner
        run: |
          trivy ${{ secrets.DOCKERHUB_USERNAME }}/wiki:${{ github.run_number }} \
          --severity CRITICAL \
          --exit-code 1 \
          --fail-on '3'
          
      -
        name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/wiki:${{ github.run_number }}
